[manifest]
version = "1.0.0"
priority = 2147483647

[[patches]]
[patches.regex]
target = "functions/state_events.lua"
pattern = '''function end_round\(\)(?<pre>[\s\S]+?)func = function\(\)'''
position = 'at'
payload = "function end_round()$pre func = G.LOBBY.code and G.MULTIPLAYER.end_round or function()"
match_indent = false
times = 1