[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483647

[[patches]]
[patches.regex]
target = "functions/state_events.lua"
pattern = '''function end_round\(\)(?<pre>[\s\S]+?)func = function\(\)'''
position = 'at'
payload = "function end_round()$pre func = G.LOBBY.code and G.MULTIPLAYER.end_round or function()"
match_indent = false
times = 1

[[patches]]
[patches.regex]
target = "game.lua"
pattern = '''function Game:update_round_eval\(dt\)(?<pre>[\s\S]+?)if not G.STATE_COMPLETE then'''
position = 'at'
payload = '''function Game:update_round_eval(dt)$pre if not G.STATE_COMPLETE and not G.MULTIPLAYER_GAME.prevent_eval then
        G.MULTIPLAYER_GAME.prevent_eval = true'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local t =   create_UIBox_generic_options({no_back = from_game_over, no_esc = from_game_over, contents ={'''
position = 'at'
payload = '''local t = G.LOBBY.code and create_UIBox_generic_options({contents ={
    {n=G.UIT.R, config={padding = 0.0, align = "cm", colour = G.C.CLEAR}, nodes={
      {n=G.UIT.R, config={align = 'cm', padding = 0.1, no_fill = true, minh = 0, minw = 0}, nodes={
        {n=G.UIT.O, config={id = 'tab_contents', object = UIBox{definition = G.UIDEF.run_setup_option('New Run'), config = {offset = {x=0,y=0}}}}}
      }},
    }},
  }}) or create_UIBox_generic_options({no_back = from_game_over, no_esc = from_game_over, contents ={'''
match_indent = true
times = 1