version: '3.8'
services:
  socket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8788:8788"
      - "49484:8788"
    environment:
      NODE_ENV: development
    restart: unless-stopped