[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483600

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''G.GAME.dollars = G.GAME.dollars + mod'''
position = 'after'
payload = '''
    if MP.LOBBY.code then
        if MP.GAME.ce_money_manip == false then
            MP.GAME.real_money = "xyz" .. tostring(tonumber(string.sub(MP.GAME.real_money, 4, -4)) + (mod or 0)) .. "xyz"
            if tonumber(string.sub(MP.GAME.real_money, 4, -4)) ~= G.GAME.dollars then 
                MP.GAME.ce_money_manip = true
                Client.send("ce_cache")
            end
        end
    end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''local selected_back = saveTable and saveTable.BACK.name or (args.challenge and args.challenge.deck and args.challenge.deck.type) or (self.GAME.viewed_back and self.GAME.viewed_back.name) or self.GAME.selected_back and self.GAME.selected_back.name or 'Red Deck''''
position = 'after'
payload = '''
    if MP.LOBBY.code then
        if selected_back == "Yellow Deck" then MP.GAME.real_money = "xyz14xyz"
        else MP.GAME.real_money = "xyz4xyz"
        end
    end
'''
match_indent = true
times = 1

