[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483600

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''function SMODS.in_scoring(card, scoring_hand)'''
position = 'after'
payload = '''   if not scoring_hand then return false end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = "for _, area in ipairs(SMODS.get_card_areas('playing_cards')) do"
position = 'after'
payload = "if not area.cards then goto continue end"
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''functions/misc_functions.lua'''
pattern = "function localize(args, misc_cat)"
position = 'after'
payload = '''   if not args then return "ERROR" end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''engine/moveable.lua'''
pattern = "function Moveable:align_to_major()"
position = 'after'
payload = '''
if not self or not self.alignment or not self.role then return end
if not self.alignment.type or not self.alignment.prev_type then return end
if not self.alignment.offset or not self.alignment.prev_offset then return end
if not self.alignment.offset.x or not self.alignment.offset.y then return end
if not self.alignment.prev_offset.x or not self.alignment.prev_offset.y then return end
if not self.T then return end
if not self.Mid or not self.Mid.T or not self.Mid.T.w or not self.Mid.T.h or not self.Mid.T.x or not self.Mid.T.y then return end
if not self.role.major or not self.role.major.T then return end
if not self.role.major.T.w or not self.role.major.T.h or not self.role.major.T.x or not self.role.major.T.y then return end
if not self.T.w or not self.T.h or not self.T.x or not self.T.y then return end
if not self.role.offset then self.role.offset = {} end'''
match_indent = true
times = 1
